title: Boxout Horsens
description: Podcast dedikeret til musik - hvor passionen er i centrum
url: https://rasmusboegildk-bot.github.io/boxouthorsens
baseurl: /boxouthorsens

# Build settings
theme: null
plugins: []

# Exclude from processing
exclude:
  - .gitignore
  - README.md
  - node_modules

# Enable markdown support
markdown: kramdown
